### PR TITLE
General Combat Improvements

### LINKED ISSUE #129: AutoEZ

### LINKED ISSUE #168: Tracer and CrystalAura colors and rendering options
- [x] crystalaura
  - [x] colors 
- [x] tracer colors

### LINKED ISSUE #362: AntiChainPop

### LINKED ISSUE #439: CrystalAura break attempts setting
A setting of how many times to try to break a crystal before giving up, because of ping.

### LINKED ISSUE #480: CrystalAura safer option, and improve hitbox detection
the title is a mouthfull, but If crystalaura can take player health into account and also calculate for damage, it can be optimized. also im not sure how long it's been since the place was updated, but it seems like it places slower than other clients. also, add an option to shrink hitboxes of certain entities that do not interact with the player (crystals, arrows, items) and also players, so the client will try to place when enemies are in the middle of two by 1 gaps but the hitbox stops crystal placement.

Heph added a customizable minimum damage as well, and a hit delay

### LINKED ISSUE #486: CrystalAura manual targeting

### LINKED ISSUE #515: Pop Counter
counts how many times a player pops. useful if you have existing information about your enemy. optional announcer that sends a chat message when a player pops a totem.

### LINKED ISSUE #534: CrystalAura don't break when holding sword

### LINKED ISSUE #543: Show tracer custom colors for friends, not enemies

### LINKED ISSUE #553: Crystalaura minimum damage

### LINKED ISSUE #554: CrystalAura break delay

### LINKED ISSUE #603: Smart offhand items for autototem

### LINKED ISSUE #613: Rare crash with getBlastReduction in safecrystal branch
Latest commit. Notice line 424 calling the method which crashes at line 446. 
@pol-y-mer plox fix pls

Apparently the person was doing nothing so this could be caused by null entity or something?

[L#424](https://github.com/S-B99/kamiblue/blob/08410d50174f77e5cd8fd3e9059fe4f2e621cadc/src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalAura.java#L424)
[L#446](https://github.com/S-B99/kamiblue/blob/08410d50174f77e5cd8fd3e9059fe4f2e621cadc/src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalAura.java#L446)
<details>
    <summary>Stacktrace</summary>

```
[12:48:21] [main/FATAL] [net.minecraft.client.Minecraft]: Unreported exception thrown!
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429) ~[?:1.8.0_74]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1453) ~[?:1.8.0_74]
        at java.util.AbstractCollection.addAll(AbstractCollection.java:343) ~[?:1.8.0_74]
        at java.util.HashSet.<init>(HashSet.java:119) ~[?:1.8.0_74]
        at com.google.common.collect.Sets.newHashSet(Sets.java:273) ~[guava-21.0.jar:?]
        at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_180375_b(SourceFile:204) ~[wh.class
        at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_111129_g(SourceFile:186) ~[wh.class
        at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_111126_e(SourceFile:176) ~[wh.class
        at net.minecraft.entity.EntityLivingBase.func_70658_aO(EntityLivingBase.java:1343) ~[vp.class:?]
        at me.zeroeightsix.kami.module.modules.combat.CrystalAura.getBlastReduction(CrystalAura.java:446) ~[Crysta
        at me.zeroeightsix.kami.module.modules.combat.CrystalAura.calculateDamage(CrystalAura.java:424) ~[CrystalA
        at me.zeroeightsix.kami.module.modules.combat.CrystalAura.onUpdate(CrystalAura.java:288) ~[CrystalAura.cla
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_74]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_74]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_74]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_74]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_74]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_74]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_74]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_74]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_74]
        at me.zeroeightsix.kami.module.ModuleManager.onUpdate(ModuleManager.java:58) ~[ModuleManager.class:?]
        at me.zeroeightsix.kami.event.ForgeEventProcessor.onTick(ForgeEventProcessor.java:73) ~[ForgeEventProcesso
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_74_ForgeEventProcessor_onTick_ClientTickEven
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHa
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349) ~[FMLCommonH
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1910) ~[bib.class:?]
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097) ~[bib.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

</details>

### PR DESCRIPTION
**Pull request by S-B99**
Not merging until finished, just using this to organize issues. 
Closes #480, closes #168, closes #543, closes #534, closes #553, closes #554, closes #486, closes #129, closes #362, closes #515, closes #603, closes #439, closes #613

Won't do: #406

### CODE REVIEW

**Comment by pol-y-mer** [comment]
looking good :flushed: cant belive my ca edits are actually going to work well

**Comment by pol-y-mer** [comment]
rename kami blue to pogware

File: src/main/java/me/zeroeightsix/kami/command/commands/SayCommand.java [hunk 1]
```diff
@@ -0,0 +1,26 @@
+package me.zeroeightsix.kami.command.commands;
+
+import me.zeroeightsix.kami.command.Command;
+import me.zeroeightsix.kami.command.syntax.ChunkBuilder;
+
+/**
+ * @author S-B99
+ * Created by S-B99 on 12/03/20
+ */
+public class SayCommand extends Command {
```
Comment (cookiedragon234) [inline src/main/java/me/zeroeightsix/kami/command/commands/SayCommand.java]: The whole purpose of this command suggests there is a problem in your command parsing. Why not for example allow a prefix to be prepended with `\` in order to prevent it being parsed as a command?

File: src/main/java/me/zeroeightsix/kami/gui/kami/KamiGUI.java [hunk 2]
```diff
@@ -423,7 +423,11 @@ public void onTick() {
                 int hposX = (int) (mc.player.posX * f);
                 int hposZ = (int) (mc.player.posZ * f);
 
-                coordsLabel.setText(String.format(" %sf%,d%s7, %sf%,d%s7, %sf%,d %s7(%sf%,d%s7, %sf%,d%s7, %sf%,d%s7)",
+                String direction = mc.player.getHorizontalFacing().toString().substring(0, 1).toUpperCase();
```
Comment (cookiedragon234) [inline src/main/java/me/zeroeightsix/kami/gui/kami/KamiGUI.java]: `substring(0, 1)` should be equal to `charAt(0)`

File: src/main/java/me/zeroeightsix/kami/module/modules/chat/AntiSpam.java [hunk 3]
```diff
@@ -75,55 +75,61 @@
...
+        } else {
+            return detectSpam(removeUsername(message));
+        }
+    }
 
-        if (wordsLongerThen.getValue() && findPatterns(FilterPatterns.LONG_WORD, message)) return sendResult(wordsLongerThen.getName(), message);
+    private String removeUsername(String username) { return username.replaceAll("<[^>]*> ", ""); }
 
-        if (greenText.getValue() && findPatterns(FilterPatterns.GREEN_TEXT, message)) return sendResult(greenText.getName(), message);
+    private boolean detectSpam(String message) {
```
Comment (cookiedragon234) [inline src/main/java/me/zeroeightsix/kami/module/modules/chat/AntiSpam.java]: What the hell am I witnessing. What on earth. Just add all of these to a map or something and loop over it!

File: src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoEZ.java [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+import me.zero.alpine.listener.Listener;
+import me.zeroeightsix.kami.module.Module;
+import me.zeroeightsix.kami.module.ModuleManager;
+import me.zeroeightsix.kami.setting.Setting;
+import me.zeroeightsix.kami.setting.Settings;
+import net.minecraft.entity.player.EntityPlayer;
+import net.minecraftforge.event.entity.player.AttackEntityEvent;
+
+/**
+ * @author polymer
```
Comment (cookiedragon234) [inline src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoEZ.java]: What did polymer make?

File: src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoEZ.java [hunk 5]
```diff
@@ -0,0 +1,61 @@
...
+ * Updated by S-B99 on 10/04/20
+ */
+@Module.Info(name = "AutoEZ", category = Module.Category.COMBAT, description = "Sends an insult in chat after killing someone")
+public class AutoEZ extends Module {
+	private Setting<Mode> mode = register(Settings.e("Mode", Mode.ONTOP));
+	EntityPlayer focus;
+	int hasBeenCombat;
+	enum Mode {GG, ONTOP, EZD, EZ_HYPIXEL, NAENAE }
+
+	private String getText(Mode m) {
```
Comment (cookiedragon234) [inline src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoEZ.java]: This could be represented by this:
```Java
enum Mode {
GG("gg, "),
ONTOP("KAMI BLUE on top! ez "),
EZD("You just got ez'd ")
...

public final String text;
private Mode(String text) {
	this.text = text;
}
}

private String getText(Mode m) {
	return m.text;
}
```

File: src/main/java/me/zeroeightsix/kami/module/modules/combat/VisualRange.java [hunk 6]
```diff
@@ -6,67 +6,58 @@
...
 /**
  * Created on 26 October 2019 by hub
  * Updated 12 January 2020 by hub
+ * Updated by polymer on 23/02/20
  */
 @Module.Info(name = "VisualRange", description = "Shows players who enter and leave range in chat", category = Module.Category.COMBAT)
 public class VisualRange extends Module {
-
     private Setting<Boolean> leaving = register(Settings.b("Leaving", false));
+    private Setting<Boolean> uwuAura = register(Settings.b("UwU Aura", false));
```
Comment (cookiedragon234) [inline src/main/java/me/zeroeightsix/kami/module/modules/combat/VisualRange.java]: Delet

File: src/main/java/me/zeroeightsix/kami/module/modules/combat/VisualRange.java [hunk 7]
```diff
@@ -6,67 +6,58 @@
...
                 if (!knownPlayers.contains(playerName)) {
-
                     knownPlayers.add(playerName);
 
                     if (Friends.isFriend(playerName)) {
                         sendNotification(ChatFormatting.GREEN.toString() + playerName + ChatFormatting.RESET.toString() + " entered the Battlefield!");
                     } else {
                         sendNotification(ChatFormatting.RED.toString() + playerName + ChatFormatting.RESET.toString() + " entered the Battlefield!");
                     }
+                    if (uwuAura.getValue()) Command.sendServerMessage("/w "+ playerName + " hi uwu");
```
Comment (cookiedragon234) [inline src/main/java/me/zeroeightsix/kami/module/modules/combat/VisualRange.java]: Delet

File: src/main/java/me/zeroeightsix/kami/module/modules/combat/VisualRange.java [hunk 8]
```diff
@@ -75,10 +66,10 @@ public void onUpdate() {
                         } else {
                             sendNotification(ChatFormatting.RED.toString() + playerName + ChatFormatting.RESET.toString() + " left the Battlefield!");
                         }
+                        if (uwuAura.getValue()) Command.sendServerMessage(("/w "+ playerName + " bye uwu"));
```
Comment (cookiedragon234) [inline src/main/java/me/zeroeightsix/kami/module/modules/combat/VisualRange.java]: Delet

File: src/main/java/me/zeroeightsix/kami/module/modules/experimental/FancyChat.java [hunk 9]
```diff
@@ -0,0 +1,114 @@
...
+ * @author S-B99
+ * Updated by S-B99 on 12/03/20
+ */
+@Module.Info(name = "FancyChat", category = Module.Category.EXPERIMENTAL, description = "Makes messages you send fancy", showOnArray = Module.ShowOnArray.OFF)
+public class FancyChat extends Module {
+    private Setting<Mode> modeSetting = register(Settings.e("Mode", Mode.MOCKING));
+    private Setting<Boolean> randomSetting = register(Settings.booleanBuilder("Random Case").withValue(true).withVisibility(v -> modeSetting.getValue().equals(Mode.MOCKING)).build());
+    private Setting<Boolean> commands = register(Settings.b("Commands", false));
+
+    private enum Mode { UWU, LEET, MOCKING }
```
Comment (cookiedragon234) [inline src/main/java/me/zeroeightsix/kami/module/modules/experimental/FancyChat.java]: How many delets are necessary?

File: src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraFlight.java [hunk 10]
```diff
@@ -100,6 +105,14 @@ protected void onDisable() {
         mc.player.capabilities.allowFlying = false;
     }
 
+    private float getHighwaySpeed() {
```
Comment (cookiedragon234) [inline src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraFlight.java]: What lol why are there two different speeds

File: src/main/java/me/zeroeightsix/kami/util/VectorUtil.java [hunk 11]
```diff
@@ -0,0 +1,159 @@
...
+        return new Vec3d(blockpos.x, blockpos.y, blockpos.z);
+    }
+    
+    public static Vec3d advanceVec(Vec3d startVec, Vec3d destinationVec, double distance) {
+        Vec3d advanceDirection = destinationVec.subtract(startVec).normalize();
+        if (destinationVec.distanceTo(startVec) < distance) return destinationVec;
+        return advanceDirection.scale(distance);
+    }
+    
+    public static List<Vec3d> getVectorsInArea(Vec3d pos1, Vec3d pos2) {
```
Comment (cookiedragon234) [inline src/main/java/me/zeroeightsix/kami/util/VectorUtil.java]: This is pretty bad

File: src/main/java/me/zeroeightsix/kami/command/Command.java [hunk 12]
```diff
@@ -56,18 +57,22 @@ public static void sendRawChatMessage(String message) {
...
+    public static void sendServerMessage(String message) {
+        if (isSendable()) {
+            Wrapper.getPlayer().connection.sendPacket(new CPacketChatMessage(message));
         } else {
-            return true;
+            LogWrapper.warning("Could not send server message: \"" + message + "\"");
         }
     }
 
+    public static boolean isSendable() {
```
[the remark this answers is not in the document]
Comment (S-B99) [reply src/main/java/me/zeroeightsix/kami/command/Command.java]: It's used twice.

File: src/main/java/me/zeroeightsix/kami/command/commands/DupeBookCommand.java [hunk 13]
```diff
@@ -0,0 +1,61 @@
...
+        super("dupebook", new ChunkBuilder().append("name").build());
+        setDescription("Generates books used for chunk savestate dupe.");
+    }
+
+    @Override
+    public void call(String[] args) {
+        ItemStack is = Wrapper.getPlayer().inventory.getCurrentItem();
+
+        if (is.getItem() instanceof ItemWritableBook) {
+            IntStream characterGenerator = new Random().ints(0x80, 0x10ffff - 0x800).map(i -> i < 0xd800 ? i : i + 0x800);
```
[the remark this answers is not in the document]
Comment (S-B99) [reply src/main/java/me/zeroeightsix/kami/command/commands/DupeBookCommand.java]: I have no idea how that works, you'd need to talk to 0x2E on Discord, I'll ask them about it

File: src/main/java/me/zeroeightsix/kami/module/modules/combat/VisualRange.java (hunk 7 above)
Comment (S-B99) [reply src/main/java/me/zeroeightsix/kami/module/modules/combat/VisualRange.java]: smh my head

File: src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraFlight.java (hunk 10 above)
Comment (S-B99) [reply src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraFlight.java]: One allows you to go past the set limit.

File: src/main/java/me/zeroeightsix/kami/util/VectorUtil.java (hunk 11 above)
Comment (S-B99) [reply src/main/java/me/zeroeightsix/kami/util/VectorUtil.java]: @Vonr can fix pls

File: src/main/java/me/zeroeightsix/kami/command/commands/SayCommand.java (hunk 1 above)
Comment (S-B99) [reply src/main/java/me/zeroeightsix/kami/command/commands/SayCommand.java]: Actually this already works, you're right, it was completely unnecessary.

File: src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoEZ.java (hunk 4 above)
Comment (S-B99) [reply src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoEZ.java]: that's the joke lol
i talked to them about it and apparently it turned out identical to yours /shrug

File: src/main/java/me/zeroeightsix/kami/command/Command.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (cookiedragon234) [reply src/main/java/me/zeroeightsix/kami/command/Command.java]: Its not long enough to justify a function, its literally just an ifnull

File: src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoEZ.java (hunk 4 above)
Comment (cookiedragon234) [reply src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoEZ.java]: 🤔  very suss

File: src/main/java/me/zeroeightsix/kami/util/VectorUtil.java (hunk 11 above)
Comment (Vonr) [reply src/main/java/me/zeroeightsix/kami/util/VectorUtil.java]: very bad is not something i can fix

**Comment by Vonr** [comment]
i literally dont know what you want me to fix

File: src/main/java/me/zeroeightsix/kami/command/commands/DupeBookCommand.java (hunk 13 above)
[the remark this answers is not in the document]
Comment (Vonr) [reply src/main/java/me/zeroeightsix/kami/command/commands/DupeBookCommand.java]: used hex because thats the clientcommands code (mod made by the discoverer of the glitch)

[the remark this answers is not in the document]
Comment (Vonr) [reply src/main/java/me/zeroeightsix/kami/command/commands/DupeBookCommand.java]: see https://github.com/Earthcomputer/clientcommands/blob/master/src/main/java/net/earthcomputer/clientcommands/command/CommandBook.java

**Comment by S-B99** [comment]
As polymer is working on his own Kami skid now, I think I'm ready to merge without doing wall range.

**Comment by S-B99** [comment]
I got the a-ok from him. Will do this later today
